version: '3'
services:
  laravel:
    image: nginx:stable-alpine
    container_name: vue-laravel-skelton_laravel-nginx
    ports:
      - 7001:80
    volumes:
      - ./laravel:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./php-fpm
    container_name: vue-laravel-skelton_php-fpm
    volumes:
      - ./laravel:/var/www/html
#      - vendor-volume:/opt/laravel/vendor
#      - storage-volume:/opt/laravel/storage
  reverse-proxy:
    image: nginx:stable-alpine
    container_name: vue-laravel-skelton_reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
  vue-cli:
    build: ./vue-cli
    container_name: vue-laravel-skelton_vue-cli
    ports:
      - 7000:80
  mysql:
   image: mysql:8.0
   container_name: vue-laravel-skelton_mysql
   environment:
     MYSQL_DATABASE: laravel
     MYSQL_ROOT_PASSWORD: laravel
     MYSQL_USER: laravel
     MYSQL_PASSWORD: laravel
     TZ: Asia/Tokyo
   ports:
     - 3307:3306
   volumes:
#     - .mysql/data:/var/lib/mysql
     - ./initdb.d:/docker-entrypoint-initdb.d
#     - db-volume:/var/lib/mysql

#volumes:
#  storage-volume:
#    driver: local
#  vendor-volume:
#    driver: local
#  db-volume:
#    driver: local
